"""Collect every interface text of the editor into src/editor/strings.lua (the localisation template's list).

    py tools/locale_strings.py           # rewrite src/editor/strings.lua
    py tools/locale_strings.py --check   # exit 1 when it is out of date (the tests run this)

Texts are the literal arguments of L('...') in src/, plus the labels the code passes to L() through variables: tab,
category and weapon-group labels, preset actions and custom stratagem fields.
"""
import re
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
SRC = PROJECT / 'src' / 'editor'
OUTPUT = SRC / 'strings.lua'
LITERAL = r"'((?:[^'\\]|\\.)*)'"


def unescape(text):
    return re.sub(r"\\(.)", lambda m: {'n': '\n', 't': '\t'}.get(m.group(1), m.group(1)), text)


def collect():
    found = []
    for path in sorted(SRC.rglob('*.lua')):
        if 'generated' in path.parts or path == OUTPUT:
            continue
        text = path.read_text(encoding='utf-8')
        found += re.findall(r"\bL\(" + LITERAL + r"\)", text)
        if path.name in ('app.lua', 'views.lua', 'catalog.lua'):
            # labels of tables the code localises at draw time
            found += re.findall(r"\blabel=" + LITERAL, text)
        for name in ('PRESET_ACTIONS', 'WEAPON_GROUPS', 'GROUP_LABELS'):
            m = re.search(r'\b' + name + r'=\{(.*?)\}\n', text, re.S)
            if m:
                found += re.findall(LITERAL, m.group(1))
    out, seen = [], set()
    for s in (unescape(x) for x in found):
        if s and s not in seen and not s.isspace():
            seen.add(s)
            out.append(s)
    return sorted(out, key=str.lower)


def render(strings):
    def lua(s):
        return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n') + "'"
    lines = ['-- Generated by tools/locale_strings.py: every interface text of the editor (the localisation template).',
             '-- Do not edit; run the tool after changing texts.', 'return {']
    lines += ['    ' + lua(s) + ',' for s in strings]
    lines.append('}')
    return '\n'.join(lines) + '\n'


def main():
    body = render(collect())
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.is_file() else ''
    if '--check' in sys.argv:
        if current != body:
            print('src/editor/strings.lua is out of date: run py tools/locale_strings.py')
            return 1
        return 0
    OUTPUT.write_text(body, encoding='utf-8', newline='\n')
    print('%d texts -> %s' % (body.count('\n') - 4, OUTPUT.relative_to(PROJECT)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
